# Generated by Django 4.2.7 on 2023-11-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_project', '0002_additions_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='divisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value1', models.IntegerField()),
                ('Value2', models.IntegerField()),
                ('result', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='multiplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value1', models.IntegerField()),
                ('Value2', models.IntegerField()),
                ('result', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='subtractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value1', models.IntegerField()),
                ('Value2', models.IntegerField()),
                ('result', models.IntegerField()),
            ],
        ),
    ]
